services:
  - type: web
    name: niqichik-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn niqichik.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Niqichik.settings
      - key: PYTHON_VERSION
        value: 3.6
