# Generated by Django 3.2.25 on 2025-06-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='session_key',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('producto', 'session_key')},
        ),
        migrations.RemoveField(
            model_name='like',
            name='usuario',
        ),
    ]
