# Generated by Django 3.2.25 on 2025-06-04 18:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_auto_20250604_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
