# Generated by Django 3.2.25 on 2025-07-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_auto_20250623_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprador_nombre', models.CharField(max_length=100)),
                ('comprador_contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
                ('productos', models.ManyToManyField(to='tienda.Producto')),
            ],
        ),
    ]
